import React, { useState } from 'react';
import { InputSection } from './components/InputSection';
import { ReportRenderer } from './components/ReportRenderer';
import { Scratchpad } from './components/Scratchpad';
import { CitationTool } from './components/CitationTool';
import { executeResearch } from './services/gemini';
import { ResearchState } from './types';

const App: React.FC = () => {
  const [state, setState] = useState<ResearchState>({
    status: 'idle',
    data: null,
    error: null,
    groundingSourceUrls: []
  });
  const [currentQuery, setCurrentQuery] = useState('');
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saved'>('idle');

  const handleSearch = async (query: string) => {
    setState(prev => ({ ...prev, status: 'loading', error: null }));
    setCurrentQuery(query);
    setSaveStatus('idle');
    
    try {
      const result = await executeResearch(query);
      setState({
        status: 'success',
        data: result,
        error: null,
        groundingSourceUrls: result.sourceUrls
      });
    } catch (err: any) {
      setState(prev => ({
        ...prev,
        status: 'error',
        error: err.message
      }));
    }
  };

  const handleReset = () => {
    setState({
        status: 'idle',
        data: null,
        error: null,
        groundingSourceUrls: []
    });
    setCurrentQuery('');
    setSaveStatus('idle');
  };

  const handleExportPDF = () => {
    const element = document.getElementById('report-container');
    if (!element) return;

    // Clone the element to modify styles for PDF without affecting the UI
    const clone = element.cloneNode(true) as HTMLElement;
    // Force darker background and ensuring text contrast for PDF print
    clone.style.backgroundColor = '#0f172a'; // slate-900
    clone.style.color = '#e2e8f0'; // slate-200
    clone.style.padding = '40px';
    
    // Create a temporary container
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '1200px'; // Fixed width for consistent PDF layout
    container.appendChild(clone);
    document.body.appendChild(container);

    const opt = {
        margin: [15, 15, 15, 15],
        filename: `DeepSeeker_Report_${new Date().toISOString().slice(0, 10)}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { 
            scale: 2, 
            useCORS: true, 
            logging: false,
            backgroundColor: '#0f172a',
            windowWidth: 1200
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    // @ts-ignore
    if (window.html2pdf) {
        // @ts-ignore
        window.html2pdf().set(opt).from(clone).save().then(() => {
            document.body.removeChild(container);
        });
    } else {
        alert('PDF generation library not loaded.');
        document.body.removeChild(container);
    }
  };

  const handleExportMarkdown = () => {
      if (!state.data?.report) return;

      const fullContent = `# ${currentQuery}\n\nGenerated by DeepSeeker Intelligence\nDate: ${new Date().toLocaleDateString()}\n\n---\n\n${state.data.report}`;
      const blob = new Blob([fullContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `DeepSeeker_Report_${new Date().toISOString().slice(0, 10)}.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
  };

  const handleSave = () => {
    if (!state.data) return;
    
    try {
        const savedReports = JSON.parse(localStorage.getItem('deepseeker_saved_reports') || '[]');
        const newReport = {
            id: Date.now(),
            query: currentQuery || "Research Report",
            date: new Date().toISOString(),
            data: state.data,
            groundingSourceUrls: state.groundingSourceUrls
        };
        
        savedReports.push(newReport);
        localStorage.setItem('deepseeker_saved_reports', JSON.stringify(savedReports));
        setSaveStatus('saved');
        
        setTimeout(() => setSaveStatus('idle'), 3000);
    } catch (e) {
        console.error("Failed to save report", e);
        alert("Failed to save report to local storage.");
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 selection:bg-cyan-900 selection:text-white pb-20">
      {/* Navigation/Header Bar */}
      <nav className="w-full border-b border-slate-800 bg-slate-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
            <div 
                onClick={handleReset}
                className="font-mono font-bold text-xl tracking-tight text-cyan-500 cursor-pointer hover:text-cyan-400 transition-colors flex items-center gap-2"
            >
                <div className="w-3 h-3 bg-cyan-500 rounded-sm rotate-45"></div>
                DEEPSEEKER
            </div>
            {state.status === 'success' && (
                <button 
                    onClick={handleReset}
                    className="text-xs font-mono text-slate-400 hover:text-white border border-slate-800 px-3 py-1.5 rounded hover:border-slate-600 transition-all"
                >
                    NEW QUERY
                </button>
            )}
        </div>
      </nav>

      <main className="container mx-auto px-4 md:px-6">
        {state.status === 'idle' && (
           <InputSection onSubmit={handleSearch} isLoading={false} />
        )}

        {state.status === 'loading' && (
            <div className="flex flex-col items-center justify-center min-h-[60vh]">
                <InputSection onSubmit={() => {}} isLoading={true} />
                <div className="mt-12 space-y-4 max-w-md w-full">
                     <div className="flex items-center gap-4 text-cyan-400 font-mono text-sm animate-pulse">
                        <div className="w-2 h-2 bg-cyan-400 rounded-full"></div>
                        <span>Triangulating Research Vectors...</span>
                     </div>
                     <div className="h-1 w-full bg-slate-900 rounded-full overflow-hidden">
                        <div className="h-full bg-cyan-600 w-1/3 animate-[shimmer_2s_infinite_linear] rounded-full"></div>
                     </div>
                     <div className="space-y-2 pt-4">
                        <div className="flex justify-between text-xs text-slate-600 font-mono">
                            <span>ACADEMIC</span>
                            <span className="text-cyan-800">SCANNING</span>
                        </div>
                        <div className="flex justify-between text-xs text-slate-600 font-mono">
                            <span>MARKET</span>
                            <span className="text-cyan-800">VALIDATING</span>
                        </div>
                        <div className="flex justify-between text-xs text-slate-600 font-mono">
                            <span>TECHNICAL</span>
                            <span className="text-cyan-800">EXTRACTING</span>
                        </div>
                     </div>
                </div>
            </div>
        )}

        {state.status === 'error' && (
            <div className="max-w-3xl mx-auto mt-20 p-8 border border-red-900/50 bg-red-950/10 rounded-xl text-center">
                <div className="text-red-500 font-mono mb-4 text-xl">SYSTEM_FAILURE</div>
                <p className="text-slate-400 mb-6">{state.error}</p>
                <button 
                    onClick={handleReset}
                    className="bg-slate-800 hover:bg-slate-700 text-white px-6 py-2 rounded-lg transition-colors font-mono text-sm"
                >
                    REBOOT SYSTEM
                </button>
            </div>
        )}

        {state.status === 'success' && state.data && (
            <div className="max-w-5xl mx-auto mt-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
                <Scratchpad content={state.data.scratchpad} />
                
                {/* ID added for PDF generation target */}
                <div id="report-container" className="bg-slate-900 border border-slate-800/60 rounded-xl p-8 md:p-12 shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-cyan-600 via-blue-600 to-purple-600"></div>
                    <div className="absolute top-4 right-4 text-[10px] font-mono text-slate-600 border border-slate-800 px-2 py-1 rounded">
                        CONFIDENTIAL // EYES ONLY
                    </div>
                    
                    {/* Display Query in PDF */}
                    <div className="mb-8 border-b border-slate-800 pb-8">
                         <h1 className="text-2xl md:text-3xl font-serif font-bold text-white mb-2">{currentQuery}</h1>
                         <div className="text-xs font-mono text-slate-500 uppercase tracking-widest">Intelligence Report • {new Date().toLocaleDateString()}</div>
                    </div>

                    <ReportRenderer markdown={state.data.report} />

                    <CitationTool markdown={state.data.report} />

                    {state.groundingSourceUrls.length > 0 && (
                         <div className="mt-16 pt-8 border-t border-slate-800">
                            <h4 className="text-xs font-mono font-bold text-slate-500 uppercase tracking-wider mb-4">Verified Grounding Sources</h4>
                            <div className="flex flex-wrap gap-2">
                                {state.groundingSourceUrls.map((url, i) => (
                                    <a 
                                        key={i} 
                                        href={url} 
                                        target="_blank" 
                                        rel="noopener noreferrer"
                                        className="text-[10px] font-mono text-cyan-700 bg-cyan-950/30 border border-cyan-900/30 px-3 py-1 rounded hover:bg-cyan-900/50 hover:text-cyan-400 transition-colors truncate max-w-[200px]"
                                    >
                                        {new URL(url).hostname}
                                    </a>
                                ))}
                            </div>
                         </div>
                    )}
                </div>

                {/* Action Buttons */}
                <div className="mt-8 flex flex-col md:flex-row items-center justify-center gap-4 pb-12 flex-wrap">
                     <button
                        onClick={handleSave}
                        disabled={saveStatus === 'saved'}
                        className={`
                            px-6 py-3 rounded-lg font-mono text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 shadow-lg min-w-[200px] justify-center
                            ${saveStatus === 'saved' 
                                ? 'bg-green-900/20 text-green-400 border border-green-900/50' 
                                : 'bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white border border-slate-700'
                            }
                        `}
                     >
                        {saveStatus === 'saved' ? (
                            <>
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                </svg>
                                Saved
                            </>
                        ) : (
                            <>
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                                </svg>
                                Save
                            </>
                        )}
                     </button>
                     
                     <button
                        onClick={handleExportPDF}
                        className="bg-cyan-900/30 text-cyan-400 hover:bg-cyan-900/50 hover:text-cyan-200 border border-cyan-900/50 px-6 py-3 rounded-lg font-mono text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 shadow-lg min-w-[200px] justify-center"
                     >
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                        </svg>
                        PDF Export
                     </button>

                     <button
                        onClick={handleExportMarkdown}
                        className="bg-slate-800 text-slate-300 hover:bg-slate-700 hover:text-white border border-slate-700 px-6 py-3 rounded-lg font-mono text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-2 shadow-lg min-w-[200px] justify-center"
                     >
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                             <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                        Markdown
                     </button>
                </div>
                
                <div className="mt-4 text-center text-slate-600 text-sm font-serif italic">
                    Generated by DeepSeeker v1.0 • Gemini 2.5 Flash
                </div>
            </div>
        )}
      </main>
    </div>
  );
};

export default App;